version: '3'

vars:
  BIGBANG_DIR: dist/bigbang
  BIGBANG_K3D_CHART: chart

tasks:
  default:
    cmds:
      - task: clone-bigbang
      - task: test
      - task: test-cluster

  clone-bigbang:
    desc: Clone bigbang from repo1 if its not already cloned
    cmds:
      - if [ ! -d "{{.BIGBANG_DIR}}" ]; then git clone https://repo1.dso.mil/big-bang/bigbang dist/bigbang; fi

  test:
    desc: Run helm lint
    cmds:
      - helm lint chart

  test-cluster:
    desc: Test cluster setup
    cmds:
      - mkdir -p dist
      - echo "Generating bootstrap.yaml (flux + metallb)"
      - helm template k3d "{{.BIGBANG_K3D_CHART}}"
        --set=registry1.username=$REGISTRY1_USERNAME 
        --set=registry1.password=$REGISTRY1_PASSWORD > dist/bootstrap.yaml
      - echo "Generating k3d-config"
      - helm template k3d "{{.BIGBANG_K3D_CHART}}"
        --set=k3d.volumeBaseDir=$(pwd)/dist
        --set=registry1.username=$REGISTRY1_USERNAME
        --set=registry1.password=$REGISTRY1_PASSWORD
        --show-only=templates/k3d-config.yaml > dist/k3d.yaml
      - k3d cluster delete --config dist/k3d.yaml && k3d cluster create --config dist/k3d.yaml
